version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Preparing application for deployment..."
      - zip -r ../application.zip *

artifacts:
  files:
    - ../application.zip
